version: '3.3'
services:
  app:
    container_name: 'golaundry_kasir'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    stdin_open: true
    environment:
      - PORT=7314
    command: npm start
volumes:
  node_modules: